version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "34:c9:75:9a:d3:2c:35:50:14:5e:ec:88:e0:15:bb:25"
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@35.228.98.103 "cd Ambitine_backend; git pull"
            ssh root@35.228.98.103 "cd Ambitine_backend; sudo docker kill ambitine_backend_ambitine_1"
            ssh root@35.228.98.103 'cd Ambitine_backend; sudo docker rm ambitine_backend_ambitine_1'
            ssh root@35.228.98.103 "cd Ambitine_backend; sudo docker-compose up -d"


# hi)
#            ssh ntn@35.228.75.3 git clone https://github.com/Pickausernaame/Ambitine_backend.git


workflows:
  version: 2
  workflow:
    jobs:
      - deploy
