version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "43:57:31:94:df:f1:77:18:ed:2b:73:16:41:b8:ec:7c"
      - run:
          name: Deploy Over SSH
          command: |
            ssh ntn@35.228.98.103 "cd Ambitine_backend; git pull"
            ssh ntn@35.228.98.103 "cd Ambitine_backend; sudo docker stop ambitine || true"
            ssh ntn@35.228.98.103 "cd Ambitine_backend; sudo docker rm ambitine || true"
            ssh ntn@35.228.98.103 "cd Ambitine_backend; sudo docker-compose up --build -d"
            ssh ntn@35.228.98.103 "sudo docker container prune -y"
            ssh ntn@35.228.98.103 "sudo docker image prune -y"

workflows:
  version: 2
  workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
