version: 2
jobs:
  build:
      docker:
        - image: circleci/golang:1.12
      working_directory: ~/Ambitine
      steps:
        - checkout
        - run: go get -v -u
        #- run: go run main.go

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "a9:6b:be:d5:9d:97:0f:38:6a:05:7a:d0:0a:ee:d1:73"
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@104.248.254.28 "cd Ambitine_backend; git pull"
            ssh root@104.248.254.28 "cd Ambitine_backend; sudo docker kill ambitine_backend_ambitine_1"
            ssh root@104.248.254.28 'cd Ambitine_backend; sudo docker rm ambitine_backend_ambitine_1'
            ssh root@104.248.254.28 "cd Ambitine_backend; sudo docker-compose up -d"


# hi)
#            ssh ntn@35.228.75.3 git clone https://github.com/Pickausernaame/Ambitine_backend.git


workflows:
  version: 2
  workflow:
    jobs:
      - deploy
